name = "pico"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-01-24"
compatibility_flags = ["nodejs_compat"]

# KV binding for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "81546b1ac32c4739b8c39a2b0e940d3e"

[[d1_databases]]
binding = "DB"
database_name = "pico-db"
database_id = "dd0f53e9-329a-447e-b977-1c4dfea3c810"
